name: Build with Docker Direct
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 1. Run the Official Kivy Container
      - name: Build APK with Docker
        run: |
          # Allow the container to write to our folder
          sudo chmod 777 .
          
          # Run the command inside the virtual machine
          # ADDED: --network host (This gives the container internet access)
          sudo docker run --rm \
          --network host \
          -v "$PWD":/home/user/hostcwd \
          kivy/buildozer \
          android debug

      # 2. Upload the result
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
