name: Build Android APK
on:
  workflow_dispatch:      # <--- This creates a "Run" button for you
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      # 1. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # 2. Install Buildozer
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # 3. Install System Libraries
      - name: Install Linux Libs
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-dev \
          libltdl-dev autoconf automake libtool pkg-config cmake \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 openjdk-17-jdk unzip zip

      # 4. Build the APK
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # 5. Upload the APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
